mineral_catalog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'', include('minerals.urls', namespace='minerals')),
    url(r'^admin/', admin.site.urls),
]

minerals/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^detail/(?P<pk>\d+)/$', views.detail, name='detail'),
    url(r'random/$', views.random, name='random'),
]

minerals/models.py
from django.db import models


class Mineral(models.Model):
    name = models.CharField(max_length=255)
    image_filename = models.CharField(max_length=255)
    image_caption = models.CharField(max_length=255)
    category = models.CharField(max_length=255)
    formula = models.CharField(max_length=255)
    strunz_classification = models.CharField(max_length=255)
    crystal_system = models.CharField(max_length=255)
    unit_cell = models.CharField(max_length=255)
    color = models.CharField(max_length=255)
    crystal_symmetry = models.CharField(max_length=255)
    cleavage = models.CharField(max_length=255)
    mohs_scale_hardness = models.CharField(max_length=255)
    luster = models.CharField(max_length=255)
    streak = models.CharField(max_length=255)
    diaphaneity = models.CharField(max_length=255)
    optical_properties = models.CharField(max_length=255)
    refractive_index = models.CharField(max_length=255)
    crystal_habit = models.CharField(max_length=255)
    specific_gravity = models.CharField(max_length=255)

    def __str__(self):
        return self.name

minerals/views.py
from django.shortcuts import render, redirect
import random

from .models import Mineral


def index(request):
    minerals = Mineral.objects.all()
    return render(request, 'minerals/index.html', {'minerals': minerals})


def detail(request, pk):
    mineral = Mineral.objects.get(pk=pk)
    return render(request, 'minerals/detail.html', {'mineral': mineral})


def random(request):
    mineral = Mineral.objects.all().order_by('?')[0]
    return redirect('minerals:detail', pk=mineral.pk)
    # return render(request, 'minerals/detail.html', {'mineral': mineral})

minerals/templates/minerals/detail.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}
<div class="grid-100 mineral__container">
  <h1 class="mineral__name">{{ mineral }}</h1>
  <div class="mineral__image-bg">
      {% with 'images/'|add:mineral.image_filename as static_image %}
        <img class="mineral__image" src="{% static static_image %}">
      {% endwith %}
    <p class="mineral__caption">{{ mineral.image_caption }}</p>
  </div>
  <div class="mineral__table-container">
    <table class="mineral__table">
      <tr>
        <td class="mineral__category">Category</td>
        <td>{{ mineral.category|title }}</td>
      </tr>
      <tr>
        <td class="mineral__category">Formula</td>
        <td class="mineral__formula">{{ mineral.formula|safe }}</td>
      </tr>
      <tr>
        <td class="mineral__category">Strunz Classification</td>
        <td>{{ mineral.strunz_classification }}</td>
      </tr>
      <tr>
        <td class="mineral__category">Unit Cell</td>
        <td>{{ mineral.unit_cell|title }}</td>
      </tr>
      <tr>
        <td class="mineral__category">Color</td>
        <td>{{ mineral.color|title }}</td>
      </tr>
      <tr>
        <td class="mineral__category">Crystal Habit</td>
        <td>{{ mineral.crystal_habit|title }}</td>
      </tr>
      <tr>
        <td class="mineral__category">Mohs Scale Hardness</td>
        <td>{{ mineral.mohs_scale_hardness }}</td>
      </tr>
    </table>
  </div>
</div>
{% endblock %}

minerals/templates/minerals/index.html
{% extends 'layout.html' %}

{% block content %}
<div class="grid-100">
    <ul class="minerals__container">
        {% for mineral in minerals %}
        <li class="minerals__item">
            <a class="minerals__anchor" href="{% url 'minerals:detail' pk=mineral.pk %}">{{ mineral }}</a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Macky's Minerals: A magnificant catalog of minerals</title>
  <meta name="description" content="">
  <meta name="author" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="{% static 'css/global.css' %}">
</head>
<body>
  <div class="bounds">
    <div class="grid-100">
      <a href="{% url 'minerals:index' %}">
        <svg class="logo" viewBox="0 0 127.6 84.8" preserveAspectRation="xMinYMin meet">
          <polygon points="42.7,84.8 49.6,79.4 40,62.5 51.2,43.5 51.2,43.5 25,0 0,55.6 "/>
          <polygon class="logo--middle" points="52.9,79.5 52.9,79.5 84.8,80.1 59.7,35 43.3,62.4 "/>
          <polygon points="127.6,61.4 127.6,61.4 110.3,13.5 110.3,13.5 70.3,48.1 70.3,48.1 88.3,80.5 95.3,81.4 95.3,81.4 "/>
        </svg>
        <h1 class="logo__name text-centered">Macky's Minerals</h1>
      </a>
      <p class="logo__text text-centered">They're not rocks!</p>
    </div>
    {% block content %}{% endblock %}
  </div>
  <div class="minerals__random">
    <a class="minerals__anchor" href="{% url 'minerals:random' %}">Show random mineral</a>
  </div>
</body>
</html>